### PR TITLE
SQLite3 Adapter

### PR DESCRIPTION
**Pull request by m43nu**
Hi there

Again a pull request now with a working sample, tested in a rails application.

Greetings
m43nu

### CODE REVIEW

**Comment by emmanuelmillionaer** [comment]
Where can i get the gem with the changings? Thanks! Im new to programming

**Comment by m43nu** [comment]
@ emmanuelmillionaer Just place this in your gem-file:

```
gem 'birthday', :git => 'git://github.com/m43nu/birthday.git'
```

**Comment by emmanuelmillionaer** [comment]
@m43nu You really helped me a lot! Thanks

**Comment by bumi** [comment]
hej! thanks a lot for the pull request. this is awesome. 
sorry, that it took so long to reply. _shocked_ :)
I'm testing it now and releasing a new version of the gem.

**Comment by emmanuelmillionaer** [comment]
@bumi is the gem yet released? I have big problems with the old gem and rails 4! Thanks for this awesome gem!

**Comment by bumi** [comment]
Yeah, the new version is pushed. Let me know if it works for you.
I am currently not using the gem in a new Rails application so it would be
great to hear if everything is OK for you.

If you want I can also give you push access for the project.

Thanks a lot for your participation! <3

Michael Bumann

F       +49 (0) 176 22747893
E       hello@michaelbumann.com
T       twitter.com/bumi

**Comment by kmmndr** [comment]
Hi all :-) 
What's happening with the new release with include Sqlite support ?
Do you think you might merge the pull request ?
We would really like it :-)

**Pull request merged**
